### ISSUE TITLE
Error ortográfico en README.md

### ISSUE THREAD

**Issue by StunxFS** [LatinoDocs/Manual-Latino#1]
Hola! yo de nuevo xD

en el README.md hay un error ortográfico
![imagen](https://user-images.githubusercontent.com/56417208/85905942-e0c54680-b7da-11ea-81ed-147d95d3432e.png)
'anterios' no es, es 'anterior'

PD: La doc está guay :100:!
PD2: Intentaré ayudar en el desarrollo de la doc como pueda.

**Comment by MelvinG24** [comment]
@StunxFS Muchas gracias por tu ayuda, en verdad que le hace bien a este proyecto.
y gracias por el cumplido. La verdad que migrar la documentación a esta nueva plataforma da trabajo XD
